import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#335c00",
        "on-surface": "#2e3335",
        "on-primary-fixed": "#264800",
        "on-tertiary-fixed-variant": "#1a5177",
        "tertiary-fixed": "#a1d1fe",
        "on-tertiary-container": "#0a476d",
        "inverse-on-surface": "#9b9d9e",
        "secondary-dim": "#5a4c75",
        "surface-container-highest": "#dee3e5",
        "tertiary-container": "#a1d1fe",
        "surface-variant": "#dee3e5",
        "surface-container-high": "#e5e9eb",
        "on-error-container": "#671200",
        "secondary-fixed-dim": "#dfccfe",
        "surface-dim": "#d5dbdd",
        "surface-container-low": "#f2f4f5",
        "on-tertiary-fixed": "#003351",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#aeb3b5",
        "on-secondary": "#fef7ff",
        "on-error": "#fff7f6",
        "primary-fixed": "#aef764",
        "secondary-fixed": "#ebdcff",
        error: "#aa371c",
        "primary-container": "#aef764",
        "error-dim": "#821a01",
        "on-secondary-container": "#594a74",
        outline: "#767c7e",
        "tertiary-fixed-dim": "#93c3ef",
        "inverse-primary": "#b3fd69",
        "on-background": "#2e3335",
        secondary: "#675882",
        "on-secondary-fixed": "#463860",
        background: "#f8f9fa",
        "on-tertiary": "#f6f9ff",
        "inverse-surface": "#0c0f10",
        tertiary: "#31638a",
        "primary-dim": "#345e00",
        "secondary-container": "#ebdcff",
        "on-primary": "#eeffd6",
        "tertiary-dim": "#22577e",
        "surface-container": "#ebeef0",
        surface: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed-variant": "#63547e",
        "on-primary-fixed-variant": "#396700",
        "error-container": "#fa7150",
        "primary-fixed-dim": "#a0e857",
        "on-surface-variant": "#5a6062",
        primary: "#3c6b00",
        "surface-tint": "#3c6b00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
